### ISSUE TITLE
repeats weighted towards sequence ends ?

### ISSUE THREAD

**Issue by colindaven** [tolkit/telomeric-identifier#14]
Hi,

thanks, this is a valuable and user-friendly tool. 

One question - are the repeats found weighted towards sequence ends ? In other words, if I have a misassembly and telomeric repeats are present in the middle of a contig - erroneously - will they still be found ?

Most repeats I have found so far are at contig/chromosome ends, so all good so far.

Thanks

**Comment by Euphrasiologist** [comment]
Hi Colin, 

Thanks for the kind words!

In `tidk explore` the repeats found are indeed weighted toward sequence ends. The distance can be adjusted on the CLI:

https://github.com/tolkit/telomeric-identifier/blob/db4001da2483e4f9821eedbfc1dc112b34f922f5/src/main.rs#L118

Default is 150kb.

Cheers!
M

**Comment by colindaven** [comment]
Hi Max,

excellent, thanks for this confirmation. I'll have a play with the values and will probably add it to an assembly final QC pipeline I'm thinking of creating soon.

Colin
