### ISSUE TITLE
Issue with lowercase search string

### ISSUE THREAD

**Issue by gbdias** [tolkit/telomeric-identifier#19]
Hi,

I observe a change in behaviour of the search command if the string provided is lowercase.

```{bash}
wget https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/951/804/975/GCA_951804975.1_iyAntPlum1.1/GCA_951804975.1_iyAntPlum1.1_genomic.fna.gz
gunzip GCA_951804975.1_iyAntPlum1.1_genomic.fna.gz
tidk search --string TTAGG --output UPPERCASE --dir $PWD --extension bedgraph -w 1000 GCA_951804975.1_iyAntPlum1.1_genomic.fna
tidk search --string ttagg --output lowercase --dir $PWD --extension bedgraph -w 1000 GCA_951804975.1_iyAntPlum1.1_genomic.fna
```
![Screenshot 2023-09-05 at 18 03 29](https://github.com/tolkit/telomeric-identifier/assets/7614153/dca6ccac-fe34-4c14-8e34-bab5a64670cc)

- From what I can tell, if the string is uppercase it works as expected.
- However, if the search string is lowercase tidk seems to be searching N's instead (always coincide with gaps).

tidk version 0.2.31 
```
name: tidk
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - libcxx=16.0.6=hd57cbcb_0
  - tidk=0.2.31=h7133b54_2
prefix: /Users/guibo205/mambaforge/envs/tidk
```

**Comment by Euphrasiologist** [comment]
Huh interesting, I'll take a look thanks for the report!

**Comment by Euphrasiologist** [comment]
Hopefully this should be fixed in the updated code base. If you can compile/run that would be cool, otherwise I'll bump the version in a few days time.

**Comment by gbdias** [comment]
Hi @Euphrasiologist I compiled after the latest commit and the issue is now solved.
Thank you!
